#!/usr/bin/env bash
# Compiles the JavaScript packages into their `dist/`.
#
# Usage:  scripts/build_ts.sh [/path/to/react-native] [--watch]
#
# TypeScript comes from the React Native checkout's node_modules, which is where
# this repository borrows every node tool from -- see scripts/bundle.sh, which
# finds metro the same way. Nothing here has node_modules of its own, and that
# is deliberate: see js/package.json.
#
# Everything that bundles needs this to have run first, because `main` points
# into `dist/`. scripts/bundle.sh runs it for you.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

args=()
WATCH=false
for arg in "$@"; do
  case "$arg" in
    --watch) WATCH=true ;;
    *) args+=("$arg") ;;
  esac
done

RN_DIR="${args[0]:-${RN_DIR:-}}"
if [ -z "$RN_DIR" ]; then
  for candidate in "$REPO_ROOT/../react-native" "$REPO_ROOT/react-native-src"; do
    [ -d "$candidate/packages/react-native/ReactCommon" ] && { RN_DIR="$candidate"; break; }
  done
fi
[ -n "$RN_DIR" ] || { echo "error: pass the React Native checkout path, or set RN_DIR" >&2; exit 1; }
RN_DIR="$(cd "$RN_DIR" && pwd)"

TSC="$RN_DIR/node_modules/.bin/tsc"
[ -x "$TSC" ] || {
  echo "error: no tsc at $TSC" >&2
  echo "       run yarn in the React Native checkout first" >&2
  exit 1
}

# Where TypeScript finds `react` and `react-native`.
#
# Nothing here has node_modules of its own -- see js/package.json -- so tsc
# cannot resolve either by walking up from the source. Metro is told the same
# thing through `nodeModulesPaths` in js/metro.config.js; this is the type
# checker's half of that arrangement, and it is generated rather than committed
# because the checkout it points at is wherever this machine put it.
#
# Which file holds React Native's types depends on what kind of React Native
# this is, and all three cases are real:
#
#   types_generated/  what `exports["."].types` names. Built at release, so a
#                     published package has it and a source checkout does not.
#   ReactNativeApi.d.ts  the API snapshot, checked in. Present at a release tag
#                     and on main, which makes it the one to prefer here.
#   types_DEPRECATED/ the old community typings. On main, and *not* at v0.87.1 --
#                     which is how this was got wrong the first time: it is what
#                     a main checkout has, so it worked locally and failed on CI
#                     against the pinned release with twenty errors that all said
#                     "Cannot find module 'react-native'".
#
# A consumer of this package resolves React Native's own types normally and
# never sees any of this.
RN_TYPES=""
for candidate in \
  "$RN_DIR/packages/react-native/types_generated/index.d.ts" \
  "$RN_DIR/packages/react-native/ReactNativeApi.d.ts" \
  "$RN_DIR/packages/react-native/types_DEPRECATED/index.d.ts"; do
  [ -f "$candidate" ] && { RN_TYPES="$candidate"; break; }
done
[ -n "$RN_TYPES" ] || {
  echo "error: found no React Native type declarations under $RN_DIR" >&2
  echo "       looked for types_generated/index.d.ts, ReactNativeApi.d.ts," >&2
  echo "       and types_DEPRECATED/index.d.ts" >&2
  exit 1
}

REACT_TYPES="$RN_DIR/node_modules/@types/react"
[ -d "$REACT_TYPES" ] || {
  echo "error: no @types/react at $REACT_TYPES" >&2
  echo "       run yarn in the React Native checkout first" >&2
  exit 1
}

PATHS_FILE="$REPO_ROOT/packages/react-native-basalt/tsconfig.paths.json"
cat > "$PATHS_FILE" <<JSON
{
  "//": "Generated by scripts/build_ts.sh. Not source; see .gitignore.",
  "compilerOptions": {
    "paths": {
      "react-native": ["$RN_TYPES"],
      "react": ["$REACT_TYPES"],
      "react/*": ["$REACT_TYPES/*"]
    },
    "typeRoots": ["$RN_DIR/node_modules/@types"],
    "types": ["node"]
  }
}
JSON

PACKAGES=("$REPO_ROOT/packages/react-native-basalt")

# Checked but not built. Everything in these is in react-native.config.js's
# load path, which React Native's CLI reads as plain CommonJS out of
# node_modules, so none of it can go behind a build. The files opt into
# checking with `// @ts-check`.
CHECKED=(
  "$REPO_ROOT/packages/react-native-basalt-gtk"
  "$REPO_ROOT/packages/react-native-basalt-appkit"
  "$REPO_ROOT/packages/react-native-basalt-win32"
)

for package in "${PACKAGES[@]}"; do
  [ -f "$package/tsconfig.json" ] || continue
  echo "==> building $(basename "$package")"
  if $WATCH; then
    "$TSC" --build "$package" --watch
  else
    "$TSC" --build "$package"
  fi
done

if ! $WATCH; then
  for package in "${CHECKED[@]}"; do
    [ -f "$package/tsconfig.json" ] || continue
    echo "==> checking $(basename "$package")"
    "$TSC" --noEmit -p "$package"
  done
fi

echo "==> built"
